//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.11 at 03:29:31 PM CST 
//


package cn.edu.ynu.web_service_ceair.validate_person;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.edu.ynu.web_service_ceair.validate_person package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.edu.ynu.web_service_ceair.validate_person
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RTNPERSON }
     * 
     */
    public RTNPERSON createRTNPERSON() {
        return new RTNPERSON();
    }

    /**
     * Create an instance of {@link RTNPERSON.RTNPERSONINFOLIST }
     * 
     */
    public RTNPERSON.RTNPERSONINFOLIST createRTNPERSONRTNPERSONINFOLIST() {
        return new RTNPERSON.RTNPERSONINFOLIST();
    }

    /**
     * Create an instance of {@link PERSON }
     * 
     */
    public PERSON createPERSON() {
        return new PERSON();
    }

    /**
     * Create an instance of {@link PERSON.PERSONINFOLIST }
     * 
     */
    public PERSON.PERSONINFOLIST createPERSONPERSONINFOLIST() {
        return new PERSON.PERSONINFOLIST();
    }

    /**
     * Create an instance of {@link ValidatePersonResponse }
     * 
     */
    public ValidatePersonResponse createValidatePersonResponse() {
        return new ValidatePersonResponse();
    }

    /**
     * Create an instance of {@link ValidatePersonRequest }
     * 
     */
    public ValidatePersonRequest createValidatePersonRequest() {
        return new ValidatePersonRequest();
    }

    /**
     * Create an instance of {@link RTNPERSON.RTNPERSONINFOLIST.RTNPERSONINFO }
     * 
     */
    public RTNPERSON.RTNPERSONINFOLIST.RTNPERSONINFO createRTNPERSONRTNPERSONINFOLISTRTNPERSONINFO() {
        return new RTNPERSON.RTNPERSONINFOLIST.RTNPERSONINFO();
    }

    /**
     * Create an instance of {@link PERSON.PERSONINFOLIST.PERSONINFO }
     * 
     */
    public PERSON.PERSONINFOLIST.PERSONINFO createPERSONPERSONINFOLISTPERSONINFO() {
        return new PERSON.PERSONINFOLIST.PERSONINFO();
    }

}
